### ISSUE TITLE
Bridge2 as Command Line 

### ISSUE THREAD

**Issue by imeMFK01** [maltesie/bridge2#5]
Dear @maltesie,

First of all really thanks for providing the support for windows platform :) and may I know whether bridge2 can be used as command line without any major changes?

Thanks.

**Comment by maltesie** [comment]
Hi,

no, since most of the functionality is based on the graphical interface, I did not add a command line interface and it would be difficult to do so. Which functionality would you like to use from the command line? There is a batch mode that you can use for repeating the same analysis on different files, but it produces .baf files that can only be read by bridge... If you are only interested in the bonds, I guess, I could write a command line interface for that.

Best,
Malte

**Comment by imeMFK01** [comment]
Dear @maltesie,

Much appreciated for your kind response. I am interested into below two things

(i) to check the presence of hydrogen bonds in-between the protein and protein-water
(ii) to get the centrality values 

I would be really grateful if you can spare sometime for converting both of these functionalities into command line version. Moreover, for running as a command line may I have any template script which I can use as an example?

Thanks.

**Comment by maltesie** [comment]
Hi,

sorry for the very late reply. I have too much to do with my job right now to be able to do much for bridge. I hope I can get back to this at some point, but for now, I will only deal with issues that report bugs. I hope you can still find bridge useful in its current state.

All the best,
Malte
